// Code generated by counterfeiter. DO NOT EDIT.
package k8sfakes

import (
	"context"
	"sync"

	"github.com/yulintan/k8s-mcp-server/internal/k8s"
	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd/api"
)

type FakeClientManager struct {
	BulkCreateDebugPodsStub        func(context.Context, []k8s.DebugPodTarget, string, []string, int) []k8s.DebugPodResult
	bulkCreateDebugPodsMutex       sync.RWMutex
	bulkCreateDebugPodsArgsForCall []struct {
		arg1 context.Context
		arg2 []k8s.DebugPodTarget
		arg3 string
		arg4 []string
		arg5 int
	}
	bulkCreateDebugPodsReturns struct {
		result1 []k8s.DebugPodResult
	}
	bulkCreateDebugPodsReturnsOnCall map[int]struct {
		result1 []k8s.DebugPodResult
	}
	BulkExecStub        func(context.Context, []k8s.ExecTarget, []string, int) []k8s.BulkExecResult
	bulkExecMutex       sync.RWMutex
	bulkExecArgsForCall []struct {
		arg1 context.Context
		arg2 []k8s.ExecTarget
		arg3 []string
		arg4 int
	}
	bulkExecReturns struct {
		result1 []k8s.BulkExecResult
	}
	bulkExecReturnsOnCall map[int]struct {
		result1 []k8s.BulkExecResult
	}
	BulkListPodsStub        func(context.Context, []k8s.BulkTarget, string, int) []k8s.PodListResult
	bulkListPodsMutex       sync.RWMutex
	bulkListPodsArgsForCall []struct {
		arg1 context.Context
		arg2 []k8s.BulkTarget
		arg3 string
		arg4 int
	}
	bulkListPodsReturns struct {
		result1 []k8s.PodListResult
	}
	bulkListPodsReturnsOnCall map[int]struct {
		result1 []k8s.PodListResult
	}
	CurrentContextStub        func() (string, error)
	currentContextMutex       sync.RWMutex
	currentContextArgsForCall []struct {
	}
	currentContextReturns struct {
		result1 string
		result2 error
	}
	currentContextReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	GetClientStub        func(string) (kubernetes.Interface, error)
	getClientMutex       sync.RWMutex
	getClientArgsForCall []struct {
		arg1 string
	}
	getClientReturns struct {
		result1 kubernetes.Interface
		result2 error
	}
	getClientReturnsOnCall map[int]struct {
		result1 kubernetes.Interface
		result2 error
	}
	GetDynamicClientStub        func(string) (dynamic.Interface, error)
	getDynamicClientMutex       sync.RWMutex
	getDynamicClientArgsForCall []struct {
		arg1 string
	}
	getDynamicClientReturns struct {
		result1 dynamic.Interface
		result2 error
	}
	getDynamicClientReturnsOnCall map[int]struct {
		result1 dynamic.Interface
		result2 error
	}
	GetRESTConfigStub        func(string) (*rest.Config, error)
	getRESTConfigMutex       sync.RWMutex
	getRESTConfigArgsForCall []struct {
		arg1 string
	}
	getRESTConfigReturns struct {
		result1 *rest.Config
		result2 error
	}
	getRESTConfigReturnsOnCall map[int]struct {
		result1 *rest.Config
		result2 error
	}
	RawConfigStub        func() (api.Config, error)
	rawConfigMutex       sync.RWMutex
	rawConfigArgsForCall []struct {
	}
	rawConfigReturns struct {
		result1 api.Config
		result2 error
	}
	rawConfigReturnsOnCall map[int]struct {
		result1 api.Config
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClientManager) BulkCreateDebugPods(arg1 context.Context, arg2 []k8s.DebugPodTarget, arg3 string, arg4 []string, arg5 int) []k8s.DebugPodResult {
	var arg2Copy []k8s.DebugPodTarget
	if arg2 != nil {
		arg2Copy = make([]k8s.DebugPodTarget, len(arg2))
		copy(arg2Copy, arg2)
	}
	var arg4Copy []string
	if arg4 != nil {
		arg4Copy = make([]string, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.bulkCreateDebugPodsMutex.Lock()
	ret, specificReturn := fake.bulkCreateDebugPodsReturnsOnCall[len(fake.bulkCreateDebugPodsArgsForCall)]
	fake.bulkCreateDebugPodsArgsForCall = append(fake.bulkCreateDebugPodsArgsForCall, struct {
		arg1 context.Context
		arg2 []k8s.DebugPodTarget
		arg3 string
		arg4 []string
		arg5 int
	}{arg1, arg2Copy, arg3, arg4Copy, arg5})
	stub := fake.BulkCreateDebugPodsStub
	fakeReturns := fake.bulkCreateDebugPodsReturns
	fake.recordInvocation("BulkCreateDebugPods", []interface{}{arg1, arg2Copy, arg3, arg4Copy, arg5})
	fake.bulkCreateDebugPodsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClientManager) BulkCreateDebugPodsCallCount() int {
	fake.bulkCreateDebugPodsMutex.RLock()
	defer fake.bulkCreateDebugPodsMutex.RUnlock()
	return len(fake.bulkCreateDebugPodsArgsForCall)
}

func (fake *FakeClientManager) BulkCreateDebugPodsCalls(stub func(context.Context, []k8s.DebugPodTarget, string, []string, int) []k8s.DebugPodResult) {
	fake.bulkCreateDebugPodsMutex.Lock()
	defer fake.bulkCreateDebugPodsMutex.Unlock()
	fake.BulkCreateDebugPodsStub = stub
}

func (fake *FakeClientManager) BulkCreateDebugPodsArgsForCall(i int) (context.Context, []k8s.DebugPodTarget, string, []string, int) {
	fake.bulkCreateDebugPodsMutex.RLock()
	defer fake.bulkCreateDebugPodsMutex.RUnlock()
	argsForCall := fake.bulkCreateDebugPodsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeClientManager) BulkCreateDebugPodsReturns(result1 []k8s.DebugPodResult) {
	fake.bulkCreateDebugPodsMutex.Lock()
	defer fake.bulkCreateDebugPodsMutex.Unlock()
	fake.BulkCreateDebugPodsStub = nil
	fake.bulkCreateDebugPodsReturns = struct {
		result1 []k8s.DebugPodResult
	}{result1}
}

func (fake *FakeClientManager) BulkCreateDebugPodsReturnsOnCall(i int, result1 []k8s.DebugPodResult) {
	fake.bulkCreateDebugPodsMutex.Lock()
	defer fake.bulkCreateDebugPodsMutex.Unlock()
	fake.BulkCreateDebugPodsStub = nil
	if fake.bulkCreateDebugPodsReturnsOnCall == nil {
		fake.bulkCreateDebugPodsReturnsOnCall = make(map[int]struct {
			result1 []k8s.DebugPodResult
		})
	}
	fake.bulkCreateDebugPodsReturnsOnCall[i] = struct {
		result1 []k8s.DebugPodResult
	}{result1}
}

func (fake *FakeClientManager) BulkExec(arg1 context.Context, arg2 []k8s.ExecTarget, arg3 []string, arg4 int) []k8s.BulkExecResult {
	var arg2Copy []k8s.ExecTarget
	if arg2 != nil {
		arg2Copy = make([]k8s.ExecTarget, len(arg2))
		copy(arg2Copy, arg2)
	}
	var arg3Copy []string
	if arg3 != nil {
		arg3Copy = make([]string, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.bulkExecMutex.Lock()
	ret, specificReturn := fake.bulkExecReturnsOnCall[len(fake.bulkExecArgsForCall)]
	fake.bulkExecArgsForCall = append(fake.bulkExecArgsForCall, struct {
		arg1 context.Context
		arg2 []k8s.ExecTarget
		arg3 []string
		arg4 int
	}{arg1, arg2Copy, arg3Copy, arg4})
	stub := fake.BulkExecStub
	fakeReturns := fake.bulkExecReturns
	fake.recordInvocation("BulkExec", []interface{}{arg1, arg2Copy, arg3Copy, arg4})
	fake.bulkExecMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClientManager) BulkExecCallCount() int {
	fake.bulkExecMutex.RLock()
	defer fake.bulkExecMutex.RUnlock()
	return len(fake.bulkExecArgsForCall)
}

func (fake *FakeClientManager) BulkExecCalls(stub func(context.Context, []k8s.ExecTarget, []string, int) []k8s.BulkExecResult) {
	fake.bulkExecMutex.Lock()
	defer fake.bulkExecMutex.Unlock()
	fake.BulkExecStub = stub
}

func (fake *FakeClientManager) BulkExecArgsForCall(i int) (context.Context, []k8s.ExecTarget, []string, int) {
	fake.bulkExecMutex.RLock()
	defer fake.bulkExecMutex.RUnlock()
	argsForCall := fake.bulkExecArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeClientManager) BulkExecReturns(result1 []k8s.BulkExecResult) {
	fake.bulkExecMutex.Lock()
	defer fake.bulkExecMutex.Unlock()
	fake.BulkExecStub = nil
	fake.bulkExecReturns = struct {
		result1 []k8s.BulkExecResult
	}{result1}
}

func (fake *FakeClientManager) BulkExecReturnsOnCall(i int, result1 []k8s.BulkExecResult) {
	fake.bulkExecMutex.Lock()
	defer fake.bulkExecMutex.Unlock()
	fake.BulkExecStub = nil
	if fake.bulkExecReturnsOnCall == nil {
		fake.bulkExecReturnsOnCall = make(map[int]struct {
			result1 []k8s.BulkExecResult
		})
	}
	fake.bulkExecReturnsOnCall[i] = struct {
		result1 []k8s.BulkExecResult
	}{result1}
}

func (fake *FakeClientManager) BulkListPods(arg1 context.Context, arg2 []k8s.BulkTarget, arg3 string, arg4 int) []k8s.PodListResult {
	var arg2Copy []k8s.BulkTarget
	if arg2 != nil {
		arg2Copy = make([]k8s.BulkTarget, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.bulkListPodsMutex.Lock()
	ret, specificReturn := fake.bulkListPodsReturnsOnCall[len(fake.bulkListPodsArgsForCall)]
	fake.bulkListPodsArgsForCall = append(fake.bulkListPodsArgsForCall, struct {
		arg1 context.Context
		arg2 []k8s.BulkTarget
		arg3 string
		arg4 int
	}{arg1, arg2Copy, arg3, arg4})
	stub := fake.BulkListPodsStub
	fakeReturns := fake.bulkListPodsReturns
	fake.recordInvocation("BulkListPods", []interface{}{arg1, arg2Copy, arg3, arg4})
	fake.bulkListPodsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClientManager) BulkListPodsCallCount() int {
	fake.bulkListPodsMutex.RLock()
	defer fake.bulkListPodsMutex.RUnlock()
	return len(fake.bulkListPodsArgsForCall)
}

func (fake *FakeClientManager) BulkListPodsCalls(stub func(context.Context, []k8s.BulkTarget, string, int) []k8s.PodListResult) {
	fake.bulkListPodsMutex.Lock()
	defer fake.bulkListPodsMutex.Unlock()
	fake.BulkListPodsStub = stub
}

func (fake *FakeClientManager) BulkListPodsArgsForCall(i int) (context.Context, []k8s.BulkTarget, string, int) {
	fake.bulkListPodsMutex.RLock()
	defer fake.bulkListPodsMutex.RUnlock()
	argsForCall := fake.bulkListPodsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeClientManager) BulkListPodsReturns(result1 []k8s.PodListResult) {
	fake.bulkListPodsMutex.Lock()
	defer fake.bulkListPodsMutex.Unlock()
	fake.BulkListPodsStub = nil
	fake.bulkListPodsReturns = struct {
		result1 []k8s.PodListResult
	}{result1}
}

func (fake *FakeClientManager) BulkListPodsReturnsOnCall(i int, result1 []k8s.PodListResult) {
	fake.bulkListPodsMutex.Lock()
	defer fake.bulkListPodsMutex.Unlock()
	fake.BulkListPodsStub = nil
	if fake.bulkListPodsReturnsOnCall == nil {
		fake.bulkListPodsReturnsOnCall = make(map[int]struct {
			result1 []k8s.PodListResult
		})
	}
	fake.bulkListPodsReturnsOnCall[i] = struct {
		result1 []k8s.PodListResult
	}{result1}
}

func (fake *FakeClientManager) CurrentContext() (string, error) {
	fake.currentContextMutex.Lock()
	ret, specificReturn := fake.currentContextReturnsOnCall[len(fake.currentContextArgsForCall)]
	fake.currentContextArgsForCall = append(fake.currentContextArgsForCall, struct {
	}{})
	stub := fake.CurrentContextStub
	fakeReturns := fake.currentContextReturns
	fake.recordInvocation("CurrentContext", []interface{}{})
	fake.currentContextMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientManager) CurrentContextCallCount() int {
	fake.currentContextMutex.RLock()
	defer fake.currentContextMutex.RUnlock()
	return len(fake.currentContextArgsForCall)
}

func (fake *FakeClientManager) CurrentContextCalls(stub func() (string, error)) {
	fake.currentContextMutex.Lock()
	defer fake.currentContextMutex.Unlock()
	fake.CurrentContextStub = stub
}

func (fake *FakeClientManager) CurrentContextReturns(result1 string, result2 error) {
	fake.currentContextMutex.Lock()
	defer fake.currentContextMutex.Unlock()
	fake.CurrentContextStub = nil
	fake.currentContextReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClientManager) CurrentContextReturnsOnCall(i int, result1 string, result2 error) {
	fake.currentContextMutex.Lock()
	defer fake.currentContextMutex.Unlock()
	fake.CurrentContextStub = nil
	if fake.currentContextReturnsOnCall == nil {
		fake.currentContextReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.currentContextReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClientManager) GetClient(arg1 string) (kubernetes.Interface, error) {
	fake.getClientMutex.Lock()
	ret, specificReturn := fake.getClientReturnsOnCall[len(fake.getClientArgsForCall)]
	fake.getClientArgsForCall = append(fake.getClientArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetClientStub
	fakeReturns := fake.getClientReturns
	fake.recordInvocation("GetClient", []interface{}{arg1})
	fake.getClientMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientManager) GetClientCallCount() int {
	fake.getClientMutex.RLock()
	defer fake.getClientMutex.RUnlock()
	return len(fake.getClientArgsForCall)
}

func (fake *FakeClientManager) GetClientCalls(stub func(string) (kubernetes.Interface, error)) {
	fake.getClientMutex.Lock()
	defer fake.getClientMutex.Unlock()
	fake.GetClientStub = stub
}

func (fake *FakeClientManager) GetClientArgsForCall(i int) string {
	fake.getClientMutex.RLock()
	defer fake.getClientMutex.RUnlock()
	argsForCall := fake.getClientArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientManager) GetClientReturns(result1 kubernetes.Interface, result2 error) {
	fake.getClientMutex.Lock()
	defer fake.getClientMutex.Unlock()
	fake.GetClientStub = nil
	fake.getClientReturns = struct {
		result1 kubernetes.Interface
		result2 error
	}{result1, result2}
}

func (fake *FakeClientManager) GetClientReturnsOnCall(i int, result1 kubernetes.Interface, result2 error) {
	fake.getClientMutex.Lock()
	defer fake.getClientMutex.Unlock()
	fake.GetClientStub = nil
	if fake.getClientReturnsOnCall == nil {
		fake.getClientReturnsOnCall = make(map[int]struct {
			result1 kubernetes.Interface
			result2 error
		})
	}
	fake.getClientReturnsOnCall[i] = struct {
		result1 kubernetes.Interface
		result2 error
	}{result1, result2}
}

func (fake *FakeClientManager) GetDynamicClient(arg1 string) (dynamic.Interface, error) {
	fake.getDynamicClientMutex.Lock()
	ret, specificReturn := fake.getDynamicClientReturnsOnCall[len(fake.getDynamicClientArgsForCall)]
	fake.getDynamicClientArgsForCall = append(fake.getDynamicClientArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetDynamicClientStub
	fakeReturns := fake.getDynamicClientReturns
	fake.recordInvocation("GetDynamicClient", []interface{}{arg1})
	fake.getDynamicClientMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientManager) GetDynamicClientCallCount() int {
	fake.getDynamicClientMutex.RLock()
	defer fake.getDynamicClientMutex.RUnlock()
	return len(fake.getDynamicClientArgsForCall)
}

func (fake *FakeClientManager) GetDynamicClientCalls(stub func(string) (dynamic.Interface, error)) {
	fake.getDynamicClientMutex.Lock()
	defer fake.getDynamicClientMutex.Unlock()
	fake.GetDynamicClientStub = stub
}

func (fake *FakeClientManager) GetDynamicClientArgsForCall(i int) string {
	fake.getDynamicClientMutex.RLock()
	defer fake.getDynamicClientMutex.RUnlock()
	argsForCall := fake.getDynamicClientArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientManager) GetDynamicClientReturns(result1 dynamic.Interface, result2 error) {
	fake.getDynamicClientMutex.Lock()
	defer fake.getDynamicClientMutex.Unlock()
	fake.GetDynamicClientStub = nil
	fake.getDynamicClientReturns = struct {
		result1 dynamic.Interface
		result2 error
	}{result1, result2}
}

func (fake *FakeClientManager) GetDynamicClientReturnsOnCall(i int, result1 dynamic.Interface, result2 error) {
	fake.getDynamicClientMutex.Lock()
	defer fake.getDynamicClientMutex.Unlock()
	fake.GetDynamicClientStub = nil
	if fake.getDynamicClientReturnsOnCall == nil {
		fake.getDynamicClientReturnsOnCall = make(map[int]struct {
			result1 dynamic.Interface
			result2 error
		})
	}
	fake.getDynamicClientReturnsOnCall[i] = struct {
		result1 dynamic.Interface
		result2 error
	}{result1, result2}
}

func (fake *FakeClientManager) GetRESTConfig(arg1 string) (*rest.Config, error) {
	fake.getRESTConfigMutex.Lock()
	ret, specificReturn := fake.getRESTConfigReturnsOnCall[len(fake.getRESTConfigArgsForCall)]
	fake.getRESTConfigArgsForCall = append(fake.getRESTConfigArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetRESTConfigStub
	fakeReturns := fake.getRESTConfigReturns
	fake.recordInvocation("GetRESTConfig", []interface{}{arg1})
	fake.getRESTConfigMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientManager) GetRESTConfigCallCount() int {
	fake.getRESTConfigMutex.RLock()
	defer fake.getRESTConfigMutex.RUnlock()
	return len(fake.getRESTConfigArgsForCall)
}

func (fake *FakeClientManager) GetRESTConfigCalls(stub func(string) (*rest.Config, error)) {
	fake.getRESTConfigMutex.Lock()
	defer fake.getRESTConfigMutex.Unlock()
	fake.GetRESTConfigStub = stub
}

func (fake *FakeClientManager) GetRESTConfigArgsForCall(i int) string {
	fake.getRESTConfigMutex.RLock()
	defer fake.getRESTConfigMutex.RUnlock()
	argsForCall := fake.getRESTConfigArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClientManager) GetRESTConfigReturns(result1 *rest.Config, result2 error) {
	fake.getRESTConfigMutex.Lock()
	defer fake.getRESTConfigMutex.Unlock()
	fake.GetRESTConfigStub = nil
	fake.getRESTConfigReturns = struct {
		result1 *rest.Config
		result2 error
	}{result1, result2}
}

func (fake *FakeClientManager) GetRESTConfigReturnsOnCall(i int, result1 *rest.Config, result2 error) {
	fake.getRESTConfigMutex.Lock()
	defer fake.getRESTConfigMutex.Unlock()
	fake.GetRESTConfigStub = nil
	if fake.getRESTConfigReturnsOnCall == nil {
		fake.getRESTConfigReturnsOnCall = make(map[int]struct {
			result1 *rest.Config
			result2 error
		})
	}
	fake.getRESTConfigReturnsOnCall[i] = struct {
		result1 *rest.Config
		result2 error
	}{result1, result2}
}

func (fake *FakeClientManager) RawConfig() (api.Config, error) {
	fake.rawConfigMutex.Lock()
	ret, specificReturn := fake.rawConfigReturnsOnCall[len(fake.rawConfigArgsForCall)]
	fake.rawConfigArgsForCall = append(fake.rawConfigArgsForCall, struct {
	}{})
	stub := fake.RawConfigStub
	fakeReturns := fake.rawConfigReturns
	fake.recordInvocation("RawConfig", []interface{}{})
	fake.rawConfigMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClientManager) RawConfigCallCount() int {
	fake.rawConfigMutex.RLock()
	defer fake.rawConfigMutex.RUnlock()
	return len(fake.rawConfigArgsForCall)
}

func (fake *FakeClientManager) RawConfigCalls(stub func() (api.Config, error)) {
	fake.rawConfigMutex.Lock()
	defer fake.rawConfigMutex.Unlock()
	fake.RawConfigStub = stub
}

func (fake *FakeClientManager) RawConfigReturns(result1 api.Config, result2 error) {
	fake.rawConfigMutex.Lock()
	defer fake.rawConfigMutex.Unlock()
	fake.RawConfigStub = nil
	fake.rawConfigReturns = struct {
		result1 api.Config
		result2 error
	}{result1, result2}
}

func (fake *FakeClientManager) RawConfigReturnsOnCall(i int, result1 api.Config, result2 error) {
	fake.rawConfigMutex.Lock()
	defer fake.rawConfigMutex.Unlock()
	fake.RawConfigStub = nil
	if fake.rawConfigReturnsOnCall == nil {
		fake.rawConfigReturnsOnCall = make(map[int]struct {
			result1 api.Config
			result2 error
		})
	}
	fake.rawConfigReturnsOnCall[i] = struct {
		result1 api.Config
		result2 error
	}{result1, result2}
}

func (fake *FakeClientManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClientManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ k8s.ClientManager = new(FakeClientManager)
